### ISSUE TITLE
Is it possible to use GraalVM aarch64?

### ISSUE THREAD

**Issue by rodrigorodrigues** [DeLaGuardo/setup-graalvm#12]
Hi,

Could you please let me know if is that possible to use GraalVM Aarch64?

If there's some way to pass the full link(https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-aarch64-21.0.0.2.tar.gz) in the configuration would be great.

Thanks

**Comment by DeLaGuardo** [comment]
Good idea, I will prepare the new release tomorrow. Thanks for your suggestion!

**Comment by DeLaGuardo** [comment]
After some thinking, I decided not to allow passing download link. That will break caching ability for hosted actions. But I change the structure of the parameters. Please check the branch new-parameters. There are changes in the readme file to explain the new structure. The old way (using "graalvm-version") is not gone completely and used if provided. Still, it should be a bit more natural to use separate parameters to specify graalvm, java base, and architecture versions.

**Comment by rodrigorodrigues** [comment]
Thanks @DeLaGuardo looks great the changes, is there way to pointing to that branch for testing in Github Actions or better wait merge to master?

Thanks

**Comment by DeLaGuardo** [comment]
Yes, just put branch name instead of version

**Comment by rodrigorodrigues** [comment]
@DeLaGuardo it worked like a charm I could see in the logs the GraalVM aarch64 thanks very much for your help.

https://github.com/rodrigorodrigues/spring-native-crud-mongodb/blob/master/.github/workflows/spring-native.yml#L57-L62
