### ISSUE TITLE
Unable to resolve action `DeLaGuardo/setup-graalvm@3`, unable to find version `3`

### ISSUE THREAD

**Issue by fahad-israr** [DeLaGuardo/setup-graalvm#14]
Our project uses an older version of this.
Definitely, we should update our version but shouldn't the older version still work.
Have a look at : https://github.com/starfixdev/starfix/pull/51/checks?check_run_id=2262607595

**Comment by DeLaGuardo** [comment]
You are right, thanks for pointing that out. I'll add a tag to match 3 as 3.1

**Comment by DeLaGuardo** [comment]
fixed
