### ISSUE TITLE
Java 17 with GraalVM 21.3.0 Support

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [DeLaGuardo/setup-graalvm#22]

**Comment by DeLaGuardo** [comment]
Hi! it works out of the box and if maintainers of [graalvm repo](https://github.com/graalvm/graalvm-ce-builds) will keep the same URL schema for future releases it will keep working that way.
Also I added one more task to check if combination you are talking about is really working. Please check this commit https://github.com/DeLaGuardo/setup-graalvm/commit/2ebaf4e808f403090cbecb79873354da5dbd7e09
