### ISSUE TITLE
Skip installation if GraalVM is already installed

### ISSUE THREAD

**Issue by yegor256** [DeLaGuardo/setup-graalvm#25]
I'm using your action on my self-hosted server. Every time it downloads and installs GraalVM from scratch. Would be great to make it skip the entire setup if `/usr/bin/graalvm` is already there. Maybe make a special configuration option for this?

**Comment by DeLaGuardo** [comment]
Sounds like a great feature, but what if installed graalvm version different from one declared as an argument?

Btw, please consider this action deprecated and use official action from [oracle](https://github.com/marketplace/actions/github-action-for-graalvm)
