### ISSUE TITLE
The `set-env` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by sebhoss** [DeLaGuardo/setup-graalvm#4]
Github is deprecating commands like `set-env` and `add-path` as explained in https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/. In commit 898e16cec172695b4b4724bb27b061b971e35b11 you already updated to the latest version which fixes those problems, however I think you still need to do a `npm install` and `npm run build` to get the latest versions to users of your action.

**Comment by DeLaGuardo** [comment]
@sebhoss thanks a lot for letting me know! I will update the build as soon as possible
